### ISSUE TITLE
Issue #1 - MVP Feature: User can authenticate with their Reddit account

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can authenticate with their Reddit account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will not be able to access the rest of the app's features unless they are authenticated. Users will be able to authenticate by signing into their Reddit account and authorizing the app. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-20 at 12 56 37 PM](https://user-images.githubusercontent.com/82540886/126387437-d9709c08-2751-418c-891d-37b757f2a802.png)
![Screen Shot 2021-07-20 at 12 56 34 PM](https://user-images.githubusercontent.com/82540886/126387439-548a1a5e-4eac-431f-8160-a31c8a6092cf.png)
![Screen Shot 2021-07-20 at 12 56 16 PM](https://user-images.githubusercontent.com/82540886/126387442-30b6cc84-8d3b-41f0-8197-ac8c89b8da98.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Use dbdesigner to design a database
- [x] Create the database using the CLI
- [x] Once the database is designed, update `schema.sql` to fill out the database with tables
- [x] Check pgweb to verify that the database was created accordingly

### ☁️ Server

- [x] Set up a basic express server using the .env variables
- [x] Create an authentication middleware ('/api/auth') that will check to see if requests contain a signed cookie
  - If the request does contain a cookie, use the jwt package to verify it and send a response containing the user's data as a JSON object
  - If the request does NOT contain a cookie or if the cookie is not recognized, the server should respond with a null user so the client can properly redirect the user to the sign-in page.
- [x] Create a middleware for ('/api/sign-in') which will send a response to Reddit's API using snoowrap
- [x] #9
- [x] Create another middleware that will handle reddit's redirect path. This middleware will get the query string and call the parseQueryString function in order to retrieve the authentication code.
- [x] Use snoowrap to create a requester for the user. Then, get the requester's refresh token along with the user's username and store it in the database along with a userID
- [x] Set-Cookie containing a JWT of user's data
- [x] Send a response to the client containing the user's data (payload) in its body
- [x] Catch and/or handle any errors
- [x] Test with HTTPie

### ⚡ Client

- [x] Update the App component to have states (user, isAuthorizing). 
- [x] In the App's render method, if isAuthorizing, nothing will be rendered
- [x] When the App component is mounted, send a get request to the server ('/api/auth'). The server will respond with a user object. Set the component's state with the new user object and set isAuthorizing to false.
- [x] Create an app-context.js module in the client/lib directory which creates a new React context (AppContext) and exports it
- [x] In the App component's render method, provide all rendered React elements with the context value of an object containing the user's data along with any methods of the App component.
- [x] In the App component's render method, set routes to the sign-in and home pages
- [x] In the Home component's render method, check to see if there is a user from the context. If there is no user, Redirect to the sign-in page
- [x] In the pages directory, create a new module (auth.jsx) that renders a page containing a sign in with Reddit button
- [x] Attach a click event handler to the button that sends a request to the server ('/api/sign-in')
- [x] Upon authenticating, the user should be redirected to the app's home page (which should now be visible to the user)

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
