### ISSUE TITLE
Issue #8 - MVP Feature: User can receive subscription updates while disconnected

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/final-project#18]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can receive subscription updates even if they are not connected to the server.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user allows the option to send search results to their inbox, their subscription gets added to the database. After the implementation of this feature, even if the user is not actively using the app, the server will send them updates using their subscription data from the database. (Polling rate will be much slower than if users were actively searching on the app)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create a separate .js module that when executed with node, pulls subscriptions for each user and does a one-time search, and sends fresh results to their inbox
- [x] Construct a bot requester using snoowrap and env variables
- [x] Query the database for all subscriptions
- [x] Then, for each subscription, use the keywords and subreddits to run a one-time search using snoowrap requester
- [x] If necessary, figure out how to convert the timestamp in the database to a format that can be used to easily compare it to the submisisons' timestamps.
- [x] Compare the timestamps of the found results. If it is newer than the time the subscription was created, add the thread's URL to an array
- [x] Compose a message to the user containing links to all of the found search results
- [x] Update the row in the database with the current timestamp, now()
- [x] Test with Node.js

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
