### ISSUE TITLE
Issue #2 - MVP Feature: User can view a list of search results from Reddit

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view a list of their search results from Reddit

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

 
![Screen Shot 2021-07-22 at 3 41 59 PM](https://user-images.githubusercontent.com/82540886/126718342-21bb8dba-bf07-40d3-934d-20856310716c.png)
![Screen Shot 2021-07-22 at 3 42 09 PM](https://user-images.githubusercontent.com/82540886/126718349-609422ca-8329-4162-9e28-5719fce57607.png)
![Screen Shot 2021-07-22 at 3 42 17 PM](https://user-images.githubusercontent.com/82540886/126718350-6a5fb271-4369-400c-9569-b04f6f1ae4c4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create a middleware function that checks for authorization
    - If the request doesn't contain a cookie with a JWT, throw a ClientError 'authorization required'
    - Otherwise, verify the token in the cookie and assign the user data to req.user. Call next() to allow the request to continue down the middleware stack
- [x] Create a middleware function ('/api/search') that will search for submissions given user's search terms
    - This middleware must come AFTER the authorization middleware
- [x] Using the data in req.user, query the database to verify that this user exists
- [x] If the user is not in the database, throw a authorization error
- [x] Otherwise, take the user's refresh token and use snoowrap to construct a new requester
- [x] Use the requester and the user's search criteria (req.body) to search for submissions
- [x] Send a json response back to the client with the search results (array of objects)
- [x] #11
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component that renders a paper tile which tells users to begin searching
- [x] Update the App component to display the search message if there is no active search
- [x] Create a drawer component
    - The drawer should be permanently open on desktop view
    - The drawer should be defaulted to close on mobile view
- [x] Create a header component that contains a search icon and a hamburger icon
    - The hamburger icon should only be visible on mobile view
    - When the hamburger icon is clicked, a nav drawer should appear from the left side of the screen
    - When the search icon is clicked, a search form will appear from the top side of the screen
- [x] Create a component that renders a search form 
- [x] When the search form is submitted, the form will reset, the client will display the search results page
    - The client will make a request to the server ('/api/search') containing the user's search criteria in the request body
- [x] When the user clicks on the search button on the home screen, the same search form should drop down
- [x] Create a component that renders the search page
    - The search page should display a tile for each search result stored in the component's state

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
