### ISSUE TITLE
Issue 9 - Feature: User can cancel search

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/final-project#20]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can cancel the current search

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can click a button to reveal a modal dialog asking if user wants 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-28 at 5 51 03 PM](https://user-images.githubusercontent.com/82540886/127414708-f5bc4efe-158f-49e8-bb09-9a6842ef976d.png)
![Screen Shot 2021-07-28 at 5 51 12 PM](https://user-images.githubusercontent.com/82540886/127414723-61141e6e-8b1e-4a63-b7b8-27e5d9f4e00e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Define a middleware function ('/api/cancel')
- [x] This function will be placed after the authorization middleware 
- [x] Use the user's data from req.user and get user's userId
- [x] Remove any existing subscriptions in the subscriptions table that match the userId
- [x] Send a response containing the ID of the subscription removed if applicable. The response will be null otherwise.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component that renders a modal dialog prompting users to confirm the cancellation of their search
- [x] Attach a click event handler to the CANCEL button on the search page.
- [x] If the users click this button, the modal dialog should be rendered
- [x] Attach a click event handler to the modal dialog's cancel button. If pressed, the modal dialog should close
- [x] Attach a click event handler to the modal dialog's confirm button. If pressed, the client will emit a 'disconnect' to the websocket connection and send a request to the server ('/api/cancel') and if successful, will receive the ID of the removed subscription
- [x] The user should receive some form of feedback indicating whether or not the search was cancelled.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
