### ISSUE TITLE
Feature: User can remove a listing from the page

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/final-project#21]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove a listing from the search results page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on the delete icon on a submission, that submission will be removed from the search results page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-29 at 12 54 21 PM](https://user-images.githubusercontent.com/82540886/127557266-c14583cb-91fe-41af-9829-50350a6a0b71.png)
![Screen Shot 2021-07-29 at 12 54 31 PM](https://user-images.githubusercontent.com/82540886/127557279-87f67d5a-683f-4e76-a34f-21746bda349b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [ ] Create a component that renders a modal dialog asking the user for confirmation on removing a submission
- [ ] Attach a onClick event handler to the Submission component's DeleteIcon button that opens the modal
- [ ] Attach an onClick event to the modal's cancel button which will close the modal
- [ ] Update the App component to pass the setSearchResults function via context
- [ ] Attach an onClick event handler to the modal's confirm button which will remove the selected listing from the page
- [ ] Define a function for removing the submission
- [ ] Call the filter method on the prevSearchResults and filter out the listing with a matching ID (props.submissionId === post.Id)
- [ ] Update the searchResults state which should cause a re-render and remove the listing.

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
