### ISSUE TITLE
Feature 10: User can remove all listings from the page

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/final-project#22]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can clear all search results from the search page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user presses the clear all button, they will be asked to confirm their selection. Once confirmed, all results on the search page will be removed.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-29 at 1 13 05 PM](https://user-images.githubusercontent.com/82540886/127559417-f5a82ec0-ad31-48e8-8b47-114a0cb26d4d.png)
![Screen Shot 2021-07-29 at 1 13 23 PM](https://user-images.githubusercontent.com/82540886/127559453-aeefff1f-d492-47c0-bf31-c3f57e9897ae.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component that renders a modal dialog asking users to confirm if they want to clear all search results
- [x] Update the App component to pass the setSearchResults function via context
- [x] In the component that renders the search page:
- [x] Attach a onClick event handler to the CLEAR ALL button that opens the modal dialog
- [x] When the user clicks on the modal's cancel button, the modal should close
- [x] When the user presses confirm, the searchResults state should be set to an empty array.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
