### ISSUE TITLE
Feature 11: User can refresh the page without losing previous search

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/final-project#23]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can refresh the page and retain previous search results

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user refreshes the page or revisits the app, their previous search results will be retained and displayed on the search page.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Define a function to check the URL for a query string and return an object containing key value pairs of search parameters
- [x] When the App component first mounts, check the URL for a query string. If there is a search parameter, setIsSearching to the query string.
- [x] Update the socket connection useEffect function:
    - Change the condition so it runs when isSearching state changes.
    - Instead of having it rely on state to retrieve the search parameters, get the parameters from the URL query string
    - If the search parameters are not valid, the function should just return
- [x] Change the submitSearch function in the App component so that it takes the given search parameters from the search form and pushes it to the URL as a query string and sets the isSearching state to the query string.
- [x] Update the CancelDialog component so that it changes the isSearching state to null rather than false when a search is cancelled and push to path '/search' with no queries

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
