### ISSUE TITLE
Issue #3 - MVP Feature: User can view the details of a submission

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the details of a submission

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on a submission listing, it will expand and reveal its body text/content.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![view submission desktop](https://user-images.githubusercontent.com/82540886/126912083-39f9548e-25d4-4339-9cb9-ee1d2d1ae2c9.png)
![view submission mobile](https://user-images.githubusercontent.com/82540886/126912084-d7e1790c-8d36-47d3-a583-654c0d661d54.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update the Submission component so that when users hover over it, it will show a pointer cursor
- [x] Update the Submission component to contain the post's body text/content in a collapsible element.
- [x] Update the Submission component to hold a state that tells if the body is expanded/collapsed
- [x] Create a new component, SubmissionBody, that will take the body text HTML via prop and return a sanitized version
- [x] SubmissionBody will sanitize the given HTML text using DOMPurify
- [x] Take the sanitized HTML text and assign it to the element's dangerouslySetInnerHTML prop.
- [x] Add a click event handler to the Submission component so that when users click on it, it will expand/collapse the hidden contents.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
