### ISSUE TITLE
Stretch Feature: User can be notified (via sound/taskbar) of a new search result

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/final-project#30]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can hear notification sounds every time a new search result is listed on the search page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the server sends a new search result to the client, the client will play a notification sound indicating to the user that a search has been found.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Place a sound file in the public directory

### ⚡ Client

- [x] In the App component, use a useRef hook and instantiate the audio file ( new Audio('/audio/notification.wav'))
- [x] In the App component, create a new method playNotification that instantiates the imported audio file and plays it
- [x] Update the socket connection useEffect hook to play the notification sound every time a new search result is found and displayed on the page.
- [x] Create a new useEffect hook with a condition checking for changes to the searchResults state.
- [x] If searchResults changes and its length is not zero, set an interval that changes the document's title and back, alerting users that a new result was found. 
- [x] When users move their mouse on the window, the interval should be cleared.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
