### ISSUE TITLE
Stretch Feature: User can mute/adjust notification volume

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/final-project#32]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can adjust the volume of notification sounds

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
On the search page, the user will be able to adjust the volume of notification sounds (or mute them entirely)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-30 at 12 40 06 PM](https://user-images.githubusercontent.com/82540886/127703769-619d0891-dbc7-4413-b749-e987c5c64d77.png)
![Screen Shot 2021-07-30 at 12 40 18 PM](https://user-images.githubusercontent.com/82540886/127703784-1378595a-c126-4a52-a3bb-2c9bcc9cf4ca.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update the App component to pass the notifSounds down via context
- [x] Create a new component that renders volume controls
- [x] When the user clicks on the volume icon, the volume slider will appear
- [x] As the user moves the volume slider, the volume of the notifications will be adjusted

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
