### ISSUE TITLE
Feature: User can sign-in using a demo account

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/final-project#37]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to sign-in using a demo account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to press a separate button and sign in with a demo account. This allows the user to try out the app without having to authorize their own account.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create a node module (demo-user.js) that inserts the demo account info into the database
- [x] Create a new middleware function that signs-in using the demo account
- [x] If the client sends a request to this target, the server will query the database for the demo account's info
- [x] The function will take the user's info then sign it via JWT and set it as a userToken cookie then redirect the user to the home page
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update the navbar component with a new ListItem (Demo Account) 
- [x] This ListItem should only be shown if the user is not already signed in
- [x] If the user clicks on this ListItem, the client should send a request to ('/api/sign-in-demo')

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
