### ISSUE TITLE
Issue #4 - MVP Feature: User can comment on a submission

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can send a comment on a submission

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click a button to send a comment. When the user clicks the button, a modal box will appear prompting the user to fill out a comment box and decide whether to send the comment or cancel the action.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![send comment desktop](https://user-images.githubusercontent.com/82540886/126928216-90557998-558d-454f-8ef9-254812648d98.png)
![send comment mobile](https://user-images.githubusercontent.com/82540886/126928219-4483f259-a6ba-4eb5-b886-4840b61228b9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Define a middleware function ('/api/comment'). This function should be placed after the authorization middleware
- [x] The function should take the user's refreshToken (property of req.user) and construct a new reddit requester
- [x] Use snoowrap's getSubmission and reply methods in order to send the user's message as a comment in the submission
- [x] The server will respond to the client with the newly created comment object, indicating that the action succeeded
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a React component that renders a modal containing the comment submission form
- [x] Update the submissions component to take in the submission ID as a prop
- [x] Attach a click event handler to the submission component's comment button
- [x] When the user clicks this button, the comment modal should be displayed (The ID of the submission being clicked should also be passed to the modal component)
- [x] When the user submits a non-empty form, the client will make a post request to the server ('/api/comment') containing the message in the request body
- [x] The user should receive some sort of feedback to indicate whether or not the procedure was successful.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
