### ISSUE TITLE
Issue #5 - MVP Feature: User can private message the author of a submission post

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can send a private message to the author of a post.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-26 at 12 47 39 PM](https://user-images.githubusercontent.com/82540886/127049578-eea191f2-f01b-4dec-b18e-83fa4dd1a6ae.png)
![Screen Shot 2021-07-26 at 12 47 52 PM](https://user-images.githubusercontent.com/82540886/127049613-29281a1d-caf5-4505-ac6e-1aa4b486c35e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Define a middleware function ('/api/message'). This function should be placed after the authorization middleware.
- [x] The function should verify that the author's username, subject, and message body are included in the request body.
- [x] The function should take the user's constructed requester (req.user.requester) and use Snoowrap's methods (composeMessage) in order to send a private message.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a React component (MessageDialog) that renders a modal containing the private message form
- [x] The Submissions component should pass in the author's username as a prop to the MessageDialog component
- [x] Attach a click event handler to the submission component's message button
- [x] When the user clicks this button, the message dialog should be displayed.
- [x] When the user submits a non-empty form, the client will make a post request to the server ('/api/message') containing the message and author's username in the request body.
- [x] The user should receive some sort of feedback to indicate whether or not the procedure was successful.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
