### ISSUE TITLE
Issue #6 - MVP Feature: User can subscribe to a search stream

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can subscribe to a search stream.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user searches a subreddit for keywords, they will be subscribed to a search stream that will send any new submissions posted that contain any of the keywords in its title.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-26 at 5 32 27 PM](https://user-images.githubusercontent.com/82540886/127076313-5222d153-bb14-4d50-ab3d-dd8c67e36059.png)
![Screen Shot 2021-07-26 at 5 32 42 PM](https://user-images.githubusercontent.com/82540886/127076329-80ba0baa-a392-4501-b4bc-4e2b871433a6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update the webpack config file to proxy websocket requests to the proper address
- [x] Define an authorization middleware for socket connections
- [x] The function should check every incoming socket for a cookie (socket.handshake.headers)
- [x] Verify the cookie with JWT and query the database for the user.
- [x] If there is no user (or any error occurs) do NOT throw a new error. Instead, call next passing in the error
- [x] If the user exists, assign the user's information to the socket.user property then call next() with no arguments
- [x] Replace the search middleware function ('/api/search') with a websocket connection using namespace '/search'
- [x] When the client is connected, create a submission stream using snoostorm
- [x] The user's search parameters should be found in the socket.handshake.query property
- [x] Whenever the search stream finds a new post, verify that it was posted after the search was initialized and that it contains one of the keywords in its title
- [x] If it passes the above conditions, the socket should emit the newly found Submission object to the client.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update the App component's submitSearch function to make a websocket connection with the server using the namespace, '/search'
- [x] Create a useEffect hook in the App component that will connect/disconnect the socket whenever the states, keyword or subreddit changes
- [x] The hook should have a guard to verify that keyword and subreddit are not empty strings
- [x] Make a websocket connection with the server using the namespace ('/search') and attach the user's search terms as the query
- [x] Add a listener for the "new_submission" event
- [x] The listener should take the received submission object and parse it(?)
- [x] Then add it to the list of searchResults state
- [x] Create a copy of the current searchResults state (spread syntax), use the unshift method to add the new submission to the start of the array
- [x] assign the newly copied array to the searchResults state
- [x] The useEffect hook should return a clean-up function that disconnects the socket when the component unmounts

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
