### ISSUE TITLE
Issue #7 - MVP Feature: User can have search stream results sent to their inbox

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can have search stream results sent to their reddit inbox.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When subscribing to a search stream, users have the option to toggle the 'send to inbox' option. If this option is toggled, the user will get a reddit private message whenever there is a hit containing the post's title (as subject) and its body being a link to the submission thread.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-27 at 5 48 18 PM](https://user-images.githubusercontent.com/82540886/127245748-eb348568-55eb-48a2-8559-7fc467788d73.png)
![Screen Shot 2021-07-27 at 5 48 35 PM](https://user-images.githubusercontent.com/82540886/127245763-3b839da2-2f62-4a76-9e38-2a02b3e51f97.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update the search subscription socket middleware:
- [x] If the toggleInbox query is true, create a reddit requester using the credentials for the FindKewordBot account.
- [x] Pass in an object containing the properties, userAgent, clientId, clientSecret, username, and password (env variables) to the snoowrap constructor
- [x] Update the new_submission event handler function to check if the bot requester is truthy
- [x] If so, get the user's RedditUser object by calling socket.user.requester.getMe()
- [x] THEN, use the bot requester to call composeMessage method, composing and sending the message to the user.
- [x] When the socket disconnects, query the database and insert into subscriptions table the user's search terms along with the timestamp.
- [x] Create a separate .js module that when executed with node, pulls subscriptions for each user and does a one-time search, and sends fresh results to their inbox. (MOVED TO SEPARATE FEATURE)
- [x] Test through the client
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
